#端口号
server:
  port: 8087

spring:
  application:
    name: springboot-mybatis-neo4j #服务名
  datasource:
    driver-class-name: org.neo4j.jdbc.http.HttpDriver
    name: neo4j
    password: 123456
    url: jdbc:neo4j:http://localhost:7474
  kafka:
    bootstrap-servers: 192.168.1.99:9092
    consumer:
      group-id: mygroup

mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
logging:
  level:
    com.damai.dao: debug





